
export default [
    {
      id:"01",
      Header:"Celestial Bodies",
      url:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fcollegedunia.com%2Fexams%2Fcelestial-bodies-physics-articleid-2964&psig=AOvVaw1wPZJbup6N7CAtPHrOF_At&ust=1700718469308000&source=images&cd=vfe&opi=89978449&ved=0CBIQjRxqFwoTCMDA6ZL01oIDFQAAAAAdAAAAABAE",
      desc: {
        title: "Description",
        body: "Celestial bodies are also termed as heavenly bodies. These are the objects in our space like sun, moon, planets, and many stars. These are forming a part of the vast universe in which we are living. The glorious night sky is having dotted appearance with such objects. When anyone observes them using the telescope, these are looking very fascinating. As these are so far away, we cannot see all of them using our naked eye. Thus we need the telescopes to study them Our universe is containing an amazing collection of celestial objects or astronomical objects. Though most of the observable cosmos is composed of the empty space. Still, this cold, dark void which is sparsely populated by the number of astronomical objects. These are ranging from the common to the bizarre. These are the stuff which is filled with the empty space of the universe. We all are familiar with the stars, planets, and moons. But besides these, many celestial objects, are lying with an amazing collection of other sights.These are colourful nebulae, delicate star clusters as well as the massive galaxies.Pulsars and quasars are further adding to this mystery. Also, the black holes swallow up every bit of the matter which comes too close. This search is on to identify the mysterious, invisible objects termed as dark matter.",
        
      },
      sub1: {
        title: "Stars",
        body: "Stars are giant balls of hot gases that can produce their own light. Stars give out energy by converting Hydrogen gas into Helium in their cores. Stars are gigantic in size and have an immense gravitational attraction. The sun is a medium-sized star that gives us energy and makes life possible on earth.Stars are giant balls of hot gases that can produce their own light. Stars give out energy by converting Hydrogen gas into Helium in their cores. Stars are gigantic in size and have an immense gravitational attraction.Distances to stars were first determined by the technique of trigonometric parallax, a method still used for nearby stars.When the position of a nearby star is measured from two points on opposite sides of Earth’s orbit (i.e., six months apart), a small angular (artificial) displacementis observed relative to a background of very remote (essentially fixed) stars. Using the radius of Earth’s orbit as the baselinethe distance of the star can be found from the parallactic angle, p. If p = 1″ (one second of arc), the distance of the star is 206,265 times Earth’s distance from the Sun—namely, 3.26 light-years.",
        imgurl:"",
       },
      sub2: {
        title: "planets",
        body: "Planets are large (almost) spherical objects that revolve around the sun. Planets move in fixed orbits around the sun. There are 8 planets in our solar system. Planets may be made of rocks, metals and gases like hydrogen, nitrogen and methane. The earth is also a planet and is the only known place in the universe which supports life. Planets that revolve around other stars are called exoplanets.Our solar system can be divided into three regions: the inner solar system, the outer solar system, and the Kuiper Belt and Oort Cloud. The inner, rocky planets are Mercury, Venus, Earth, and Mars. These worlds also are known as terrestrial planets because they have solid surfaces. Mercury, Earth, and Mars are currently being explored by spacecraft. Two rovers are on the surface of Mars. NASA's newest rover — Perseverance — landed on Mars on Feb. 18, 2021. Three missions are in development to return to Venus.The outer planets are gas giants Jupiter and Saturn and ice giants Uranus and Neptune. NASA's Juno spacecraft is on an extended mission at Jupiter and ESA's JUICE mission is on the way. NASA also is building Europa Clipper and Dragonfly to explore moons of Jupiter and Saturn.Beyond Neptune, a newer class of smaller worlds called dwarf planets reign, including longtime favorite Pluto. NASA's New Horizons spacecraft visited there in 2015, and is currently exploring the Kuiper Belt beyond Pluto. Thousands more planets have been discovered beyond our solar system. Scientists call them exoplanets .The word planet is derived from the word “planets” which means wanderer this name is given to them as they appear to wander in the night sky from east to west while stars also move from east to west but they seem to remain fixed relative to each other and the planet relative to them seem to move forward and backward.A planet is a celestial body that revolves around the sun in fixed orbits and planets do not have the light of their own but reflects the light of the sun they also do not twinkle like other stars as they are too close to us and till now the earth is the only known planet to harbor life and have the favorable condition.",
        imgurl:""
     },
      sub3:{
        title: "Satellites",
        body: "Satellites are objects that revolve around planets. They form the essential part of the celestial bodies. These may be of natural origin or sent by humans. The moon is a natural satellite of the earth and revolves around it because it is bound by the Earth's gravitational pull. Man has also placed artificial or man-made satellites around the earth and other planets to study them and for communication purposes.A satellite is a moon, planet or machine that orbits a planet or star. For example, Earth is a satellite because it orbits the sun. Likewise, the moon is a satellite because it orbits Earth. Usually, the word “satellite” refers to a machine that is launched into space and moves around Earth or another body in space.Earth and the moon are examples of natural satellites. Thousands of artificial, or man-made, satellites orbit Earth. Some take pictures of the planet that help meteorologists predict weather and track hurricanes. Some take pictures of other planets, the sun, black holes, dark matter or faraway galaxies. These pictures help scientists better understand the solar system and universe.Still other satellites are used mainly for communications, such as beaming TV signals and phone calls around the world. A group of more than 20 satellites make up the Global Positioning System, or GPS. If you have a GPS receiver, these satellites can help figure out your exact location.",
         imgurl:""
    },
 
      sub4: {  
       title:"Comets",
       body: "These are small chunks of ice and rock that come from the outer edge of the solar system. When its orbit brings it closer to the sun, the ice on them vaporizes, creating a beautiful tail behind them.Comets are mostly found way out in the solar system. Some exist in a wide disk beyond the orbit of Neptune called the Kuiper Belt. We call these short-period comets. They take less than 200 years to orbit the Sun.Other comets live in the Oort Cloud, the sphere-shaped, outer edge of the solar system that is about 50 times farther away from the Sun than the Kuiper Belt. These are called long-period comets because they take much longer to orbit the Sun. The comet with the longest known orbit takes more than 250,000 years to make just one trip around the Sun!.The gravity of a planet or star can pull comets from their homes in the Kuiper Belt or Oort Cloud. This tug can redirect a comet toward the Sun. The paths of these redirected comets look like long, stretched ovals. As the comet is pulled faster and faster toward the Sun, it swings around behind the Sun, then heads back toward where it came from. Some comets dive right into the Sun, never to be seen again. When the comet is in the inner solar system, either coming or going, that's when we may see it in our skies.",
       imgurl:""
    },
    sub5 : {  
       
       title:"Asteroids",
       body: "These are small irregularly shaped rocks made up of metal or minerals that orbit the sun. Most of them are found between Mars and Jupiter in an area known as the asteroid belt.There are lots of asteroids in our solar system. Most of them live in the main asteroid belt—a region between the orbits of Mars and Jupiter.Asteroids hang out in other places, too. For example, some asteroids are found in the orbital path of planets. This means that the asteroid and the planet follow the same path around the sun. Earth and a few other planets have asteroids like this.Asteroids are left over from the formation of our solar system. Our solar system began about 4.6 billion years ago when a big cloud of gas and dust collapsed. When this happened, most of the material fell to the center of the cloud and formed the sun.Some of the condensing dust in the cloud became planets. The objects in the asteroid belt never had the chance to be incorporated into planets. They are leftovers from that time long ago when planets formed.",
       imgurl:""
    },
    sub6:{  
       title:"meteors-meteorites",
       body: "These are objects from space that enter our atmosphere as they are pulled by the earth's gravity. Meteors usually are small and burn up in the atmosphere as they enter the earth. This creates streaks in the sky as though a star has fallen. They are commonly called shooting stars. If a meteor is large enough it can reach the ground and create a crater. Such objects are called meteorites.When meteoroids enter Earth’s atmosphere, or that of another planet, like Mars, at high speed and burn up, they’re called meteors. This is also when we refer to them as “shooting stars.” Sometimes meteors can even appear brighter than Venus -- that’s when we call them “fireballs.” Scientists estimate that about 48.5 tons (44,000 kilograms) of meteoritic material falls on Earth each day.When a meteoroid survives its trip through the atmosphere and hits the ground, it’s called a meteorite.Several meteors per hour can usually be seen on any given night. When there are lots more meteors, you’re watching a meteor shower. Some meteor showers occur annually or at regular intervals as the Earth passes through the trail of dusty debris left by a comet (and, in a few cases, asteroids).Meteor showers are usually named after a star or constellation that is close to where the meteors appear to originate in the sky. Perhaps the most famous are the Perseids, which peak around August 12 every year. Every Perseid meteor is a tiny piece of the comet Swift-Tuttle, which swings by the Sun every 135 years. Other notable meteor showers include the Leonids, associated with comet Tempel-Tuttle; the Aquarids and Orionids, linked to comet Halley, and the Taurids, associated with comet Encke. Most of this comet debris is between the size of a grain of sand and a pea and burns up in the atmosphere before reaching the ground. Sometimes, meteor dust is captured by high-altitude aircraft and analyzed in NASA laboratories.",
       imgurl:""
    },
    sub7:{  
       title:"galaxy",
       body: "Galaxies are large groups of stars held together by gravity. The sun and the solar system are a part of a galaxy known as the Milky Way. Other galaxies are usually so far away that they look like stars in the night sky. The Andromeda galaxy and the Large Magellanic Cloud are galaxies that can be seen with the naked eye on a clear night.The next time you go out to wonder at the night sky, try to identify these objects. If you can get a star chart, use it to find the different celestial objects mentioned in the night sky.Galaxies consist of stars, planets, and vast clouds of gas and dust, all bound together by gravity. The largest have trillions of stars and can be more than a million light-years across. The smallest can contain a few thousand stars and span just a few hundred light-years. Most large galaxies have supermassive black holes at their centers, some with billions of times the Sun’s mass. Galaxies come in a variety of shapes, mostly spirals and ellipticals, as well as those with less orderly appearances, usually dubbed irregular. Most galaxies are between 10 billion and 13.6 billion years old. Some are almost as old as the universe itself, which formed around 13.8 billion years ago. Astronomers think the youngest known galaxy formed approximately 500 million years ago. Galaxies can organize into groups of about 100 or fewer members held together by their mutual gravity. Larger structures, called clusters, may contain thousands of galaxies. Groups and clusters can be arranged in superclusters, which are not gravitationally bound. Superclusters, empty voids, “walls” of galaxies, and other large-scale structures make up the cosmic web of matter in the universe.",
       imgurl:""
    },
  },
 
 ];